version: "3.9"

services:
  postgres_database:
    restart: always
    image: postgres
    command: -p 5435
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5435
    ports:
      - "5435:5435"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: django-app:v1
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c "sh /app/scripts/entrypoint.sh"
    depends_on:
      - postgres_database

volumes:
  postgres_data:
