# Generated by Django 4.2.4 on 2024-07-12 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('mothers_maiden_name', models.CharField(max_length=100)),
                ('nin', models.CharField(max_length=20)),
                ('driving_school_certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_photo', models.ImageField(upload_to='passport_photos/')),
                ('affidavit_police_report', models.ImageField(blank=True, null=True, upload_to='affidavits/')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('state_of_residence', models.CharField(max_length=100)),
                ('local_govt_area', models.CharField(max_length=100)),
                ('application_type', models.CharField(choices=[('new', 'New Application'), ('renewal', 'Renewal'), ('reissue', 'Reissue')], max_length=20)),
                ('vehicle_type', models.CharField(choices=[('motor_vehicle', 'Motor Vehicle'), ('motorcycle_tricycle', 'Motorcycle/Tricycle')], max_length=20)),
                ('licence_id', models.CharField(blank=True, max_length=50, null=True)),
                ('appointment_location', models.CharField(max_length=255)),
                ('appointment_day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=20)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('date_of_issuance', models.DateField(blank=True, null=True)),
                ('date_of_renewal', models.DateField(blank=True, null=True)),
                ('date_of_reissuance', models.DateField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
